all:myLoading myMeminfo test

myLoading:myLoading.c
	gcc myLoading.c -g -o myLoading
myMeminfo:myMeminfo.c
	gcc myMeminfo.c -g -o myMeminfo
test:test.c
	gcc test.c -g -o test
clear:
	rm myLoading myMeminfo