all:dirio countSetuid listFullPathInDir

dirio:dirio.c
	gcc dirio.c -g -o dirio
countSetuid:countSetuid.c
	gcc countSetuid.c -g -o countSetuid
listFullPathInDir:listFullPathInDir.c
	gcc listFullPathInDir.c -g -o listFullPathInDir	
clear:
	rm dirio listFullPathInDir